# Generated by Django 5.2.1 on 2025-05-09 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Модель автомобиля')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название фирмы')),
                ('headquarters', models.CharField(blank=True, max_length=100, verbose_name='Штаб-квартира')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название страны')),
            ],
        ),
        migrations.CreateModel(
            name='CarDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Полное описание')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.car', verbose_name='Автомобиль')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='catalog.company', verbose_name='Фирма-производитель'),
        ),
        migrations.AddField(
            model_name='car',
            name='countries',
            field=models.ManyToManyField(related_name='cars', to='catalog.country', verbose_name='Страны производства'),
        ),
    ]
