# Generated by Django 5.2.1 on 2025-05-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardescription',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/', verbose_name='Фото автомобиля'),
        ),
        migrations.AlterField(
            model_name='cardescription',
            name='description',
            field=models.TextField(blank=True, verbose_name='Полное описание'),
        ),
    ]
